services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=admin
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
